# Configuracoes de desenvolvimento
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Em dev, evita cache de schema OpenAPI para refletir alteracoes apos restart
springdoc.cache.disabled=true

# Reduz ruido de warning comum em dev
spring.jpa.open-in-view=false

#OAUTH Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
