# Configuracoes de desenvolvimento
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Em dev, evita cache de schema OpenAPI para refletir alteracoes apos restart
springdoc.cache.disabled=true

# Reduz ruido de warning comum em dev
spring.jpa.open-in-view=false
